version: "3.4"
services:  
  fastfoodpostgres-svc:
    container_name: postgres-fiap
    restart: always
    build:
      context: ./Docker
      dockerfile: db.Dockerfile
    volumes:
      - ./var:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
  fastfoodapi:
    container_name: fastfood-fiap
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - fastfoodpostgres-svc
    ports:
      - 8000:80
      - 8001:443
    restart: always
    environment: 
      - DBHOST=fastfoodpostgres-svc