apiVersion: v1
kind: Pod
metadata:
  name: fastfoodapi-pod
  labels:
    app: fastfoodapi-pod
spec:
  containers:
  - name: fastfoodapi
    image: luisfernandodass/posfiapsoat
    ports:
      - name: api-port-svc
        containerPort: 80
