apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfoodapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastfoodapi-pod
  template:
    metadata:
      name: fastfoodapi-pod
      labels:
        app: fastfoodapi-pod
    spec:
      containers:
        - name: fastfoodapi
          image: brwillon/fastfoodapi
          ports:
            - name: api-port
              containerPort: 80
